import { z } from "zod";
import { AppointmentCategorySchema } from "./appointment-category.enum.js";

/**
 * Server-tool contracts — the Zod schemas that gate every webhook ElevenLabs
 * ConvAI calls during a live conversation.
 *
 * Every webhook MUST:
 *   - Validate input against the request schema; on failure return a structured
 *     error and let the agent escalate gracefully (see Section 6 guardrails).
 *   - Be idempotent on `requestId` (UUID generated by the agent).
 *   - Resolve the tenant from `agentId` (passed by ConvAI) + the agents table
 *     in Supabase.
 *
 * Latency budget per call: <1.5s p95 (ConvAI server-tool timeout ~5s).
 */

// ---- check_availability ----

export const CheckAvailabilityRequestSchema = z
  .object({
    requestId: z.string().uuid(),
    agentId: z.string(),
    /** AppointmentCategory the caller wants. Mapped to tenant calendar resources. */
    serviceCategory: AppointmentCategorySchema,
    /** Optional ISO 8601 window the caller prefers. */
    preferredWindow: z
      .object({
        from: z.string().datetime(),
        to: z.string().datetime(),
      })
      .optional(),
    /** Hint from caller language for slot-formatting in the response. */
    language: z.enum(["pl", "en", "ru"]).default("pl"),
  })
  .strict();
export type CheckAvailabilityRequest = z.infer<typeof CheckAvailabilityRequestSchema>;

export const CheckAvailabilitySlotSchema = z
  .object({
    slotId: z.string(),
    startsAt: z.string().datetime(),
    endsAt: z.string().datetime(),
    /** Display string the agent reads to the caller, pre-formatted in `language`. */
    displayLabel: z.string(),
  })
  .strict();
export type CheckAvailabilitySlot = z.infer<typeof CheckAvailabilitySlotSchema>;

export const CheckAvailabilityResponseSchema = z
  .object({
    requestId: z.string().uuid(),
    slots: z.array(CheckAvailabilitySlotSchema).max(5),
    /** True if `preferredWindow` had no matches and we widened the search. */
    widened: z.boolean().default(false),
  })
  .strict();
export type CheckAvailabilityResponse = z.infer<typeof CheckAvailabilityResponseSchema>;

// ---- create_booking ----

export const CreateBookingRequestSchema = z
  .object({
    requestId: z.string().uuid(),
    agentId: z.string(),
    /** Must be a slotId returned by the LAST `check_availability` call in this conversation. */
    slotId: z.string(),
    /** Caller's name as they said it. PII — redacted in logs. */
    patientName: z.string().min(1),
    /** E.164 if possible. PII — redacted in logs. */
    patientPhone: z.string().min(1),
    serviceCategory: AppointmentCategorySchema,
    notes: z.string().optional(),
    language: z.enum(["pl", "en", "ru"]).default("pl"),
  })
  .strict();
export type CreateBookingRequest = z.infer<typeof CreateBookingRequestSchema>;

export const CreateBookingResponseSchema = z
  .object({
    requestId: z.string().uuid(),
    bookingId: z.string().uuid(),
    smsShortUrl: z.string().url(),
    /** Display string the agent reads back as confirmation. */
    confirmationLine: z.string(),
  })
  .strict();
export type CreateBookingResponse = z.infer<typeof CreateBookingResponseSchema>;

// ---- shared error envelope ----

export const ServerToolErrorSchema = z
  .object({
    requestId: z.string().uuid().optional(),
    code: z.enum([
      "validation_failed",
      "slot_no_longer_available",
      "calendar_unreachable",
      "tenant_not_found",
      "internal",
    ]),
    /** Plain-language message the agent reads to the caller. */
    callerSafeMessage: z.string(),
  })
  .strict();
export type ServerToolError = z.infer<typeof ServerToolErrorSchema>;
